# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  # khaposbe:
  #   image: khaposbe
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 5129:5129
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=khangle@123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
